class homepage_locators:
    # Locators for the home page of the cohort manager application
    HOME_TAB = "(//div[text()='Home'])[1]"
    COHORTS_HEADING = "//h2[text()='Cohorts']"
    ACTIVE_COHORTS = "//p[contains(text(),'Active')]"
    INACTIVE_COHORTS = "//p[contains(text(),'Inactive')]"
    FIRST_COHORT = "(//tr//td[number(text()) > 0])[1]"
    SEARCH_COHORT = "//input[@placeholder='Search Cohort']"
    COHORT_DASHBOARD = "//p[text()='Cohort Dashboard']"
    DOWNLOAD_EXCEL = "//span[text()='Click to download excel file']"
    GENERAL_INFO = "//p[text()='General Info']"
    COHORT_ACTIVITY = "//span[text()='Cohort Activity']"
    UPCOMING_ACTIVITIES = "//h2[text()='Upcoming Activities']"
    CREATE_MEETING = "//p[text()='Create Meeting']"
    ENTER_MEETING_TITLE = "//label[text()='Enter Meeting Title']//following::input[1]"
    SELECT_DATE = "//input[@placeholder='Select Date']"
    # TODAY_DATE = "//td[contains(@class,'ant-picker-cell ant-picker-cell-in-view ant-picker-cell-today')]"
    TODAY_DATE = "//td[contains(@class,'ant-picker-cell ant-picker-cell-end ant-picker-cell-in-view ant-picker-cell-today')]"
    OK_BUTTON = "//span[text()='OK']"
    SELECT_TIME = "//span[@class='ant-select-selection-item']"
    CHECKBOX = "//input[contains(@class,'ant-checkbox-input')]"
    CREATE_MEETING_BUTTON = "//span[text()='Create a Meeting']"
    OKAY_BUTTON = "//span[text()='Okay']"
    TEST_HEADING = "//h5[text()='test']"
    DELETE_ICON = "//img[contains(@class,'delete-icon')]"
    RADIO_CHECK = "(//input[contains(@class,'radio-check')])[2]"
    REASON_TO_CANCEL = "(//label[contains(@class,'reason-text')])[2]"
    CANCEL_MEETING_BUTTON = "//button[contains(@class,'button-primary cancel-meeting-button  false')]"
    CLOSE_MODAL_BUTTON = "//span[@class='ant-modal-close-x']"
    COHORT_VENTURES = "//p[text()='Cohort Ventures']"
    CREATE_VENTURE = "//span[text()='Create Venture']"
    COMPANY_NAME_INPUT = "//label[text()='Company Name']//following::input[1]"
    SELECT_INDUSTRY_TYPE = "//label[contains(text(),'Select Industry Type')]/following::div[contains(@class,'ant-select-selector')][1]"
    SOFTWARE_AND_IT_SERVICES = "//div[contains(@class,'ant-select-item-option-content') and normalize-space()='Software and IT Services']"
    DESCRIPTION_INPUT = "//label[text()='Description']//following::input[1]"
    SELECT_COUNTRY = "//label[text()='Select Country']/following::div[contains(@class,'ant-select-selector')][1]"
    INDIA = "//div[contains(@class,'ant-select-item-option-content') and normalize-space()='India']"
    SELECT_CITY = "//label[text()='Select City']/following::div[contains(@class,'ant-select-selector')][1]"
    BANGALORE = "//div[contains(@class,'ant-select-item-option-content') and contains(normalize-space(),'Bangalore')]"
    NEXT_BUTTON = "//span[text()='Next']"
    STUDENT_EMAIL_INPUT = "//input[@placeholder='Enter Student Email']"
    SEND_INVITE = "//span[text()='Send Invite']"
    COHORT_VENTURES_HEADING = "//h4[contains(text(),'Cohort Ventures')]"
    FIRST_COHORT_VENTURE = "(//div[@class='section_card_container cohort-venture-card-container'])[1]"
    COHORT_MEMBERS = "//p[text()='Cohort Members']"
    COHORT_MEMBERS_HEADING = "//span[contains(text(),'Cohort Members')]"
    FIRST_COHORT_MEMBER = "(//div[@class='content_container'])[1]"
    CREATE_NEW_COHORT = "//span[text()='Create New Cohort']"
    COHORT_DETAILS_HEADING = "//div[text()='Cohort Details']"
    INSTITUTE_SELECT = "//label[text()='Institute']/following::div[@class='ant-select-selector'][1]"
    # SPARK_INSTITUTE = "//div[contains(@class,'ant-select-item-option-content') and normalize-space()='Spark Institute']"
    TESTSPARK_INSTITUTE = "//div[contains(@class,'ant-select-item-option-content') and normalize-space()='test spark']"
    DELIVERY_MODEL_DROPDOWN = "//label[text()='Delivery Model']/following::div[@class='ant-select-selector'][1]"
    SELECT_DELIVERY_MODEL = "//span[contains(@class,'ant-select-selection-item') and normalize-space()='D2C']"
    PROGRAM_SELECT = "//label[text()='Select Program']/following::div[@class='ant-select-selector'][1]"
    LIFTOFF_SPARK = "//div[contains(@class,'ant-select-item-option-content') and normalize-space()='liftoff-spark']"
    STAGE_SELECT = "//label[text()='Select Stage']/following::div[@class='ant-select-selector'][1]"
    EARLY_STAGE = "//div[contains(@class,'ant-select-item-option-content') and normalize-space()='Early Stage']"
    COHORT_NAME_INPUT = "//input[@id='batchName']"
    START_DATE_INPUT = "//input[@placeholder='start date']"
    TODAY_DATE = "//td[contains(@class,'ant-picker-cell ant-picker-cell-in-view ant-picker-cell-today')]"
    END_DATE_INPUT = "//input[@placeholder='end date']"
    END_DATE = "(//td[contains(@class,'ant-picker-cell')])[last()]"
    MAX_STUDENTS_INPUT = "//input[@placeholder='add number']"
    VENTURE_SIZE_INPUT = "//input[@placeholder='Select a number from 1 to 10 to limit venture size']"
    CREATE_BUTTON = "//span[text()='Create']"
    THREEDOTS_ICON = "//img[@alt='more-options']"
    CLOSE_COHORT= "//h1[text()='Close Cohort']"
    CLOSE_BUTTON = "//span[text()='Close']"
    FIRST_COHORT_DELETE = "(//tbody//tr[1]//td[last()])[1]"
    OFFICE_HOURS_HEADING = "//h2[text()='Office Hours']"
    CREATE_OFFICE_HOURS_BUTTON = "//span[text()='Create']"
    MEETING_TITLE_INPUT = "//label[text()='Enter Meeting Title']//following::input[1]"
    SELECT_DATE_INPUT = "//input[@placeholder='Select Date']"
    TODAY_SELECTED_DATE = "//td[contains(@class,'ant-picker-cell ant-picker-cell-in-view ant-picker-cell-today')]"
    OK_BUTTON = "//span[text()='OK']"
    SELECT_TIME_INPUT = "//span[@class='ant-select-selection-item']"
    CHECKBOX_INPUT = "//input[contains(@class,'ant-checkbox-input')]"
    CREATE_MEETING_BUTTON = "//span[text()='Create a Meeting']"
    OKAY_BUTTON = "//span[text()='Okay']"
    OFFICE_HOURS_MEETING_CARD = "//div[contains(@class,'card-wrapper meeting-card-wrapper happening_meeting')]"
    MEETING_TITLE = "//h5[text()='test']"
    DELETE_ICON = "//img[contains(@class,'delete-icon')]"
    RADIO_CHECK = "(//input[contains(@class,'radio-check')])[2]"
    REASON_TO_CANCEL = "(//label[contains(@class,'reason-text')])[2]"
    CANCEL_MEETING_BUTTON = "//button[contains(@class,'button-primary cancel-meeting-button  false')]"
    GO_BACK_TO_DASHBOARD_BUTTON = "//button[@class='button-link button-link  ']"
