class connected_ventures_locators:
    MENTOR_HOME_PAGE_HEADER = "(//div[text()='Home'])[1]"
    CONNECTED_VENTURES_MENU= "(//div[text()='Connected Ventures'])[1]"
    CONNECTED_VENTURES_CARD = "(//div[@class='ant-col ant-col-xs-24 ant-col-md-8'])[1]"
    CONNECTED_VENTURES_BOOK_SESSION_BUTTON = "(//span[text()='Book Session'])[1]"
    CONNECTED_VENTURES_MEETING_TITLE_INPUT = "//label[text()='Enter Meeting Title']//following::input[1]"
    CONNECTED_VENTURES_MEETING_DATE_INPUT = "//input[@placeholder='Select Date']"
    CONNECTED_VENTURES_MEETING_DATE_TODAY = "//td[contains(@class,'ant-picker-cell ant-picker-cell-in-view ant-picker-cell-today')]"
    CONNECTED_VENTURES_MEETING_DATE_OK_BUTTON = "//span[text()='OK']"
    CONNECTED_VENTURES_MEETING_TIME_INPUT = "//span[@class='ant-select-selection-item']"
    CONNECTED_VENTURES_MEETING_CHECKBOX = "//input[contains(@class,'ant-checkbox-input')]"
    CONNECTED_VENTURES_MEETING_CREATE_BUTTON = "//span[text()='Create a Meeting']"
    CONNECTED_VENTURES_MEETING_OK_BUTTON = "//span[text()='Okay']"
    CONNECTED_VENTURES_CHAT_BUTTON = "(//span[text()='Chat'])[1]"
