class home_cohort_locators:
    HOME_HEADER="(//div[text()='Home'])[1]"
    COHORTS_HEADER="//h2[text()='Cohorts']"
    ACTIVE_TAB="//p[contains(text(),'Active')]"
    SELECT_COHORT="(//tr//td[number(text()) > 0])[1]"
    COHORT_DASHBOARD_TAB="//p[text()='Cohort Dashboard']"
    VALIDATE_DOWNLOAD_EXCEL="//span[text()='Click to download excel file']"
    SCORE_CARD_TAB="//p[text()='Scorecard']"
    GENERAL_INFO_TAB="//p[text()='General Info']"
    VALIDATE_ADD_FACULTY_BUTTON="//span[text()='Add Faculty']"
    RELEASE_MILESTONE_TAB="//p[text()='Release Milestone']"
    COHORT_VENTURES_TAB="//p[text()='Cohort Ventures']"
    COHORT_MEMBERS_TAB="//p[text()='Cohort Members']"
    PAGE_NUMBER="//a[text()='2']"
    INACTIVE_TAB="//p[contains(text(),'Inactive')]"
    SEARCH_COHORT="//input[@placeholder='Search Cohort']"
    CREATE_NEW_ACCOUNT_BUTTON="//span[text()='Create New Cohort']"
    COHORT_DETAILS_HEADING="(//div[text()='Cohort Details'])[2]"
    INSTITUTE_DETAILS_DROPDOWN="//label[text()='Institute']/following::div[@class='ant-select-selector'][1]"
    # SELECT_INSTITUTE_DETAILS="//div[contains(@class,'ant-select-item-option-content') and normalize-space()='ins-pk-8dec']"
    SELECT_INSTITUTE_DETAILS="//div[contains(@class,'ant-select-item-option-content') and normalize-space()='qa_test_prati']"
    DELIVERY_MODEL_DROPDOWN="//label[text()='Delivery Model']/following::div[@class='ant-select-selector'][1]"
    SELECT_DELIVERY_MODEL="//div[contains(@class,'ant-select-item-option-content') and normalize-space()='D2C']"
    SELECT_COURSE_DROPDOWN="//label[text()='Select Course']/following::div[@class='ant-select-selector'][1]"
    SELECT_COURSE_OPTION="//div[contains(@class,'ant-select-item-option-content') and normalize-space()='Ignite Full']"
    SELECT_STAGE_DROPDOWN="//label[text()='Select Stage']/following::div[@class='ant-select-selector'][1]"
    SELECT_STAGE_OPTION="//div[contains(@class,'ant-select-item-option-content') and normalize-space()='Idea Stage']"
    COHORT_NAME="//input[@id='batchName']"
    START_DATE="//input[@placeholder='start date']"
    SELECT_START_DATE="//td[@class='ant-picker-cell ant-picker-cell-in-view ant-picker-cell-today']"
    SELECT_START_DATE_LAST="//td[@class='ant-picker-cell ant-picker-cell-end ant-picker-cell-in-view ant-picker-cell-today']"
    END_DATE="//input[@placeholder='end date']"
    SELECT_END_DATE="(//td[@class='ant-picker-cell'])[last()]"
    MAX_STUDENTS_ALLOWED="//input[@placeholder='add number']"
    MAX_STUDENTS_ALLOWED_PER_VENUE="//input[@placeholder='Select a number from 1 to 10 to limit venture size']"
    SAVE_NEXT="//span[text()='Save & Next']"
    COPY_COHORT_CODE="//span[text()='Copy Cohort code']"
    FIRST_COHORT_CODE="//tr[@class='ant-table-row ant-table-row-level-0'][1]//td[1]"
    COHORT_MORE_OPTIONS="//div[@id='cohort-more-options']//img"
    CLOSE_COHORT="//h1[text()='Close Cohort']"
    CLOSE_COHORT_CONFIRM="//span[text()='Close']"
    