class performance_locators:
    PERFORMANCE_SECTION="(//div[text()='Performance'])[1]"
    PLEASE_SELECT_HEADING="//span[text()='Please select the following fields to get the reports:']"
    PROGRAM_NAME="//p[text()='Program Name :']"
    PROGRAM_COURSE="(//span[contains(@class,'ant-select-selection-search')])[1]"
    PROGRAM_COURSE_OPTION="//div[contains(@class,'ant-select-item-option-content') and normalize-space()='IgniteX - 1.0']"
    STATUS="//p[text()='Status :']"
    STATUS_DROPDOWN="(//div[contains(@class,'ant-select-selector')])[2]"
    STATUS_OPTION="//div[contains(@class,'ant-select-item-option-content') and normalize-space()='Active']"
    COHORT_NAME="//p[text()='Cohort Name :']"
    COHORT_DROPDOWN="//span[text()='Select Cohort']/ancestor::div[contains(@class,'ant-select-selector')]"
    COHORT_OPTION="//div[contains(@class,'ant-select-item-option-content') and normalize-space()='IPV2-batch-28nov']"
    COHORT_QUIZ_SCORECARD="//p[text()='Cohort Quiz Scorecard']"
    QUIZ_STATUS="//span[text()='Quiz Status']"
    TOGGLE_SWITCH="(//button[contains(@class,'ant-switch toggle-switch')])[1]"
    MILESTONE_STATUS="//span[text()='Milestone Status']"
    MILESTONE_TOGGLE_SWITCH="(//button[contains(@class,'ant-switch toggle-switch')])[2]"
    DOWNLOAD_COHORT_PERFORMANCE="//span[text()='Download Cohort Performance']"
