class digital_library_locators:
	DIGITAL_LIBRARY_HEADER = "(//div[text()='Digital Library'])[1]"
	VALIDATE_DIGITAL_LIBRARY_HEADING = "//h2[text()='Digital Library']"
	VALIDATE_LATEST_ARTICLES_AND_VIDEOS = "//h4[text()='Latest Articles & Videos']"
	VALIDATE_WRU_LOOKING_FOR = "//h4[text()='What are you looking for?']"
	VALIDATE_EXPERT_VIDEOS = "//h4[text()='Expert Videos']"
	VALIDATE_CASE_STUDIES = "//h4[text()='Case Studies']"
	VALIDATE_CASELETS = "//h4[text()='Caselets']"
	VALIDATE_CONCEPT_NOTES = "//h4[text()='Concept Notes']"
	VALIDATE_SOLUTION_KITS = "//h4[text()='Solution Kits']"
	VALIDATE_GOOD_READS = "//h4[text()='Good Reads']"
	SEARCH_INPUT = "//input[@type='search']"
	FIRST_SEARCH_RESULT = "(//div[@class='cover_image_container'])[1]"
	VALIDATE_SUGGESTED_ARTICLES_VIDEOS = "//h2[text()='Suggested Articles & Videos']"
	BACK_BUTTON = "//span[text()='Back']"
