class LoginLocators:
	LOGIN_BUTTON = "//button[text()='Login']"
	EMAIL_INPUT = "//input[@id='email']"
	PASSWORD_INPUT = "//input[@id='password']"
	SIGN_IN = "//span[text()='Sign In']"
	NO_THANKS_POPUP = "//span[text()='No thanks']"
	CLOSE_POPUP_GETSTARTED = "//span[@class='ant-modal-close-x']"
	HOME = "(//div[text()='Home'])[1]"
	START_YOUR_JOURNEY_POPUP = "//h2[text()='Start your Journey: Identify your gaps']"
	NEXT_BUTTON = "//span[text()='Next']"
	CREATE_PERSONALISED_JOURNEY_POPUP = "//h2[text()='Create a personalised journey']"
	START_PROGRAM_JOURNEY_BUTTON = "//span[text()='Start program journey']"
	VALIDATE_LOGO = "//div[@class='layout_logo']//img"
	PROFILE_BUTTON = "//div[@class='header_menu_container']//span[text()='VS']"
	PROFILE_MENU = "//div[@class='ml-3 profile_container']"
	LOGOUT_BUTTON = "//h1[text()='Logout']"
