class settings_locators:
	PROFILE_ICON = "//div[@class='ml-3 profile_container']"
	SETTINGS_ICON = "//h1[text()='Settings']"
	SETTINGS_HEADER = "//h1[text()='Settings']"
	ACCOUNTS_MENU = "//h1[text()='Accounts']"
	NOTIFICATIONS_MENU = "//h1[text()='Notifications']"
	MEETING_CARD = "(//div[@class='section-container'])[1]"
	ZOOM_SETTINGS_HEADER = "//span[text()='Zoom Meetings']"
	MEETINGS_DESCRIPTION = "//h2[text()='Please click the below button to disconnect your Zoom account from this platform']"
	MEETINGS_CARD = "(//div[@class='ant-row zoom-container css-1v613y0'])[1]"
	ZOOMCONNECTION_ARROW_BUTTON = "//div[@class='ant-row navigate_container']"
	TOGGLER_OFF = "//button[@class='ant-switch wf_switch toggle_button']"
	TOGGLER_ON = "//button[@class='ant-switch wf_switch toggle_button ant-switch-checked']"
	SIGNIN_BUTTON = "//a[text()='Sign In']"
	DISCONNECT_BUTTON = "//span[text()='Disconnect']"
	BACK_ARROW = "//span[text()='Back']/preceding::img[1]"
	WHATSAPP_NOTIFICATION = "//span[text()='WhatsApp Notifications']"
	VALIDATE_WHATSAPP_NOTIFICATIONS_HEADING = "//h1[text()='WhatsApp Notifications']"
	CALENDAR_MENU = "//h1[text()='Calendar']"
	SYNC_GOOGLE_CALENDAR = "//span[text()='Sync Google Calendar']"
