class viabilityventureslocators:
    HOME= "(//div[text()='Home'])[1]"
    VENTURES= "(//div[text()='Ventures'])[1]"
    ALL_VENTURES= "//h4[text()='All Ventures']"
    PENDING_EVALUATIONS= "//p[contains(text(),'Pending Evaluations')]"
    EVALUATE_BUTTON= "//span[text()='Evaluate']"
    VENTURE_INFO_CARD= "//div[@class='venture-info']"
    SUBMISSIONS_EVALUATION_HEADINGS = "//div[text()='Submissions & Evaluation']"
    INSTRUCTIONS_HEADINGS = "//div[text()='Instructions']"
    VIEW_FILE_LINK = "//h6[text()='Please click here to view the file']"
    EVALUATE_HEADING = "//h6[text()='Evaluate']"
    MY_RATINGS_HEADING = "//p[text()='My Ratings']"
    COMPLETED_EVALUATIONS = "//p[contains(text(),'Completed Evaluations')]"
    COMPLETED_EVALUATIONS_CARD = "(//div[@class='ant-col ant-col-24 ant-col-sm-8'])[2]"    