COHORTS_HEADER="(//div[text()='Cohorts'])[1]"
DIRECT_COHORTS_HEADING="//h2[text()='Direct Cohorts']"
STATUS="(//span[text()='Status'])[1]"
ACTIVE_TAB="(//button[contains(@class,'ant-btn ant-btn-default ant-dropdown-trigger dropdown-btn') and normalize-space()='Active'])[1]"
INACTIVE_TAB="(//button[contains(@class,'ant-btn ant-btn-default ant-dropdown-trigger dropdown-btn') and normalize-space()='Inactive'])[1]"
SELECT_COHORT="(//tr//td[number(text()) > 0])[1]"
COHORT_DASHBOARD_TAB="//p[text()='Cohort Dashboard']"
VALIDATE_DOWNLOAD_EXCEL="//span[text()='Click to download excel file']"
SCORE_CARD_TAB="//p[text()='Scorecard']"
GENERAL_INFO_TAB="//p[text()='General Info']"
VALIDATE_ADD_FACULTY_BUTTON="//span[text()='Add Faculty']"
RELEASE_MILESTONE_TAB="//p[text()='Release Milestone']"
COHORT_VENTURES_TAB="//p[text()='Cohort Ventures']"
COHORT_MEMBERS_TAB="//p[text()='Cohort Members']"
PAGE_NUMBER="//a[text()='2']"
SEARCH_COHORT_INPUT="(//input[@placeholder='Search Cohort'])[1]"
INCUBATOR_COHORTS_HEADING="//h2[text()='Incubator Cohorts']"
INCUBATOR_STATUS="(//span[text()='Status'])[2]"
INCUBATOR_ACTIVE_TAB="(//button[contains(@class,'ant-btn ant-btn-default ant-dropdown-trigger dropdown-btn') and normalize-space()='Active'])[2]"
INCUBATOR_INACTIVE_TAB="(//button[contains(@class,'ant-btn ant-btn-default ant-dropdown-trigger dropdown-btn') and normalize-space()='Inactive'])[2]"
INCUBATOR_SEARCH_COHORT_INPUT="(//input[@placeholder='Search Cohort'])[2]"
INCUBATOR_FIRST_ROW_LAST_COLUMN="(//tbody[@class='ant-table-tbody']//tr[1]//td[last()])[2]"
COHORT_DASHBOARD_TAB="//p[text()='Cohort Dashboard']"
GENERAL_INFO_TAB="//p[text()='General Info']"
COHORT_MEMBERS_TAB="//p[text()='Cohort Members']"
COHORT_STARTUPS_TAB="//p[text()='Cohort Startups']"