HOME = "(//div[text()='Home'])[1]"
ASSIGNED_COHORTS_HEADING = "//h2[text()='Assigned Cohorts']"
SELECT_COHORT = "(//tr//td[number(text()) > 0])[1]"
COHORT_DASHBOARD_TAB = "//p[text()='Cohort Dashboard']"
VALIDATE_DOWNLOAD_EXCEL = "//span[text()='Click to download excel file']"
SCORE_CARD_TAB = "//p[text()='Scorecard']"
GENERAL_INFO_TAB = "//p[text()='General Info']"
VALIDATE_ADD_FACULTY_BUTTON = "//span[text()='Add Faculty']"
RELEASE_MILESTONE_TAB = "//p[text()='Release Milestone']"
RELEASE_MILESTONE = "//h4[text()='Release Milestone']//following::tr[last()]//td[5]"
CHECKBOX = "(//input[@type='checkbox'])[2]"
# EXTRACT_SUBMISSION_DATE = "//div[@class='checkbox_column_container']//caption[2]"
EXTRACT_SUBMISSION_DATE= "(//div[@class='checkbox_column_container']//caption[2])[1]"
EXTEND_DEADLINE = "//span[text()='Extend Deadline']"
SUBMISSION_DEADLINE_INPUT = "//label[text()='Submission Deadline']//following::input[1]"
OK_BUTTON = "//span[text()='OK']"
UPDATE_BUTTON = "//span[text()='Update']"
REFRESH_BUTTON = "//span[text()='Refresh']"
COHORT_VENTURES_TAB = "//p[text()='Cohort Ventures']"
COHORT_MEMBERS_TAB = "//p[text()='Cohort Members']"
PAGE_NUMBER = "//a[text()='2']"


def submission_deadline_date(submission_date):
    return f"//td[@title='{submission_date}']"
