class HomeLocators:
    HOME_HEADER = "(//div[text()='Home'])[1]"
    RESOURCE_NETWORK_HEADER = "(//div[text()='Resource Network'])[1]"
    DIGITAL_LIBRARY_HEADER = "(//div[text()='Digital Library'])[1]"
    CALENDAR_HEADER = "(//div[text()='Calendar'])[1]"
    EVENTS_HEADER = "(//div[text()='Events'])[1]"
    CHAT_BADGE_HEADER = "//span[@class='ant-badge chat_badge']"
    NOTIFICATION_BADGE_HEADER = "//span[@class='ant-badge notification__badge']"
    NOTIFICATION_CLOSE = "//img[@class='notification__title__cross']"
    PROFILE_MENU_HEADER = "//div[@class='ml-3 profile_container']"
    CERTIFICATION_SECTION = "//h3[contains(text(),'Certification Logic')]"
    PERSONALIZED_JOURNEY_SECTION = "//span[text()='Go to your Program Journey']"
    FEATURED_RESOURCE_NETWORK_SECTION = "//h4[text()='Featured Resource Network']"
    MENTOR_CARD = "(//div[@class='mentor-detail'])[1]"
    REQUEST_MEETING_BUTTON = "(//div[@class='mentor-detail'])[1]//span[text()='Request Meeting']"
    RECOMMENDED_CONTENT_SECTION = "//h4[text()='Recommended Content']"
    RECOMMENDED_BY_YOUR_INSTITUTE_SECTION = "//h2[text()='Recommended By Your Institute']"
    COURSES_SECTION = "//h4[text()='Courses']"
    FIRST_COURSE = "//div[@class='institute_program_course__slider']//li[1]"