class ignite_courses_locators:
    GO_TO_JOURNEY="(//span[text()='Go to Course'])[position()=2]"
    OVERVIEW="//P[text()='Overview']"
    COURSE_CONTENT="//P[text()='Course Content']"
    RESUME_BUTTON="//span[text()='Resume']"
    VENTURE_JOURNEY="//P[text()='Venture Journey']"
    YOUR_VENTURE_JOURNEY_HEADING="//h3[text()='Your Venture Journey']"
    VIEW_OUTPUT="(//span[text()='View Output'])[1]"
    REDO_BUTTON="(//span[text()='Redo'])[1]"
    BACK_VENTURE_JOURNEY="//div[text()='Venture Journey']"
    MILESTONE_HEADER="(//h3[contains(text(),'Milestone')])[position()=1]"
    PREVIEW_BUTTON="(//span[text()='Preview'])[1]"
    COHORT_SECTION="//span[text()='Cohort:']"
    PROGRAM_NAME="//span[text()='Program Name:']"
    SUBMISSIONS="//div[text()='Submissions']"
    INSTRUCTIONS="//div[text()='Instructions']"
    PERFORMANCE="//p[text()='Performance']"
    YOUR_PERFORMANCE="//h3[text()='Your Performance']"
    MANDATORY_CONTENT_CARD="//article[@class='performance-card performance-card--mandatoryContent']"
    QUIZZES_CARD="//article[@class='performance-card performance-card--quizzes']"
    MILESTONE_CARD="//article[@class='performance-card performance-card--milestones']"
    YOUR_CERTIFICATE="//h3[text()='Your Certificates']"
    SHARE_BUTTON="//button[@class='certificate-section__action certificate-section__action--share']"
    COPY_LINK="//span[text()='Copy Link']"
    DOWNLOAD_BUTTON="//button[@class='certificate-section__action certificate-section__action--download']"
    COHORT="(//span[text()='Cohort'])[2]"
    COHORT_GENERAL_INFO="//p[text()='General Info']"
    COHORT_VENTURES="//p[text()='Cohort Ventures']"
    COHORT_MEMBERS="//p[text()='Cohort Members']"
    MY_VENTURE="(//span[text()='My Venture'])[2]"
    IGNITE_HEADER="//span[text()='ignite']"
    WADHWANI="//span[text()='wadhwani']"
    IGNITE_VIEW_BUTTON="(//button[text()='View'])[1]"
    BASIC_INFORMATION="(//span//img)[3]"
    SAVE_BUTTON="//span[text()='Save']"
    YOUTUBE_VIDEO="//iframe[@class='media']"
    VALIDATE_VIEW_VENTURE_JOURNEY="//span[text()='View Venture Journey']"
    VENTURE_CODE="//span[text()='Venture code: ']"
    COHORT_NAME="//span[text()='Cohort Name: ']"
    PROGRAM_NAME="//span[text()='Program Name: ']"
    ABOUT_WADHWANI="(//img[@class='edit-pencil'])[2]"
    YOUTUBE_VIDEO_URL="//label[text()='Youtube Video URL']//following::input"
    VENTURE_TEAM="(//span//img)[4]"
    ADD_MEMBER="//span[text()='+ Add Member']"
    SEARCH_MEMBER="//input[@type='search']"
    SELECT_MEMBER="(//span[text()='Select'])[1]"
    ADD_MEMBERS_BUTTON="//span[text()='Add Members']"
    MEMBER_REMOVE_ICON="(//span[@class='ant-avatar ant-avatar-circle'])[5]//following::img[1]"
    CLOSE_ADD_MEMBERS_SECTION="//span[@class='ant-modal-close-x']"
    VENTURE_SUPPORT="//span[text()='Venture Support']"
    VENTURE_SUPPPORT_FACULTY="//p[text()='Faculty']"
    MILESTONE_TIMELINE="//span[text()='Milestone Timeline']"
    TEST_MILESTONE_CARD="(//div[contains(@class,'timeline-item')]//div[contains(@class,'milestone-card')])[1]"
    UPCOMING_ACTIVITIES="//h2[text()='Upcoming Activities']"
    MEETING_CARD="(//div[contains(@class,'card-wrapper')])[1]"
    WEBINAR_CARD="(//div[contains(@class,'card-wrapper')])[2]"
    RESOURCES="//h3[text()='Resources']"
    BROWSE_UPLOAD="//h2[text()='Upload Here']"
    FILE_NAME="//label[text()='File Name']"
    FILE_NAME_INPUT="//label[text()='File Name']/following::input[1]"
    SAVE_BUTTON="//span[text()='Save']"
    RESOURCES_CARD="//h2[text()='Resources']"
    MORE="//div[@class='ant-dropdown-trigger more-option']"
    VIEW_RESOURCE="//span[text()='View']"
    DELETE_RESOURCE="//span[text()='Delete']"
    VIEW_SLIDES="//p[text()='View Slides']"
    
