class liftoff_course_locators:
    HOME_HEADER="(//div[text()='Home'])[1]"
    LIFTOFF_PROGRAM="//h1[text()='Liftoff program']"
    CHOOSE_YOUR_GAPS="//p[text()='Choose your Gaps']"
    START_NOW_BUTTON="//span[text()='Start Now']"
    VALIDATE_PROGRAM_APPLICATION="//span[text()='Program Application']"
    IDENTIFY_YOUR_GAPS="//span[text()='Identify your gaps']"
    GAP_IDENTIFICATION="//h3[text()='Gap Identification']"
    YOUR_SELECTED_GAPS="//h3[text()='Your Selected Gaps']"
    ADD_MODIFY_GAPS="//span[text()='Add/Modify gaps']"
    STRATEGY_AND_PLANNING_CHECKBOX="(//h3[text()='Strategy and Planning | Business Strategy ']/ancestor::section[1]//input)[1]"
    SUBMIT_BUTTON="//span[text()='Submit']"
    PROCEED_TO_PERSONALISED_JOURNEY="//span[text()='Proceed To Personalised Journey']"
    PERSONALISED_JOURNEY="//span[text()='Personalised Journey']"
    PRODUCT_ITERATION_GAP_SECTION="//section[@id='ProductIteration']"
    WATCH_AGAIN="//span[text()='Watch again']"
    CLOSE_VIDEO="//span[@class='ant-modal-close-x']"
    SUBMIT_PITCH="//span[text()='Submit Pitch']"
    SUBMIT_YOUR_PITCH_DECK="//h3[text()='Submit your Pitch Deck']"
    UPLOAD_YOUR_PITCH_DECK="//h2[text()='Upload your Pitch Deck']"
    UPLOAD_BUTTON="//h6[text()='Upload']"
    FILE_NAME_LABEL="//label[text()='File Name']"
    FILE_NAME_INPUT="//label[text()='File Name']/following::input[1]"
    SAVE_BUTTON="//span[text()='Save']"
    PITCH_DECK_RECORD="//h2[text()='Pitch deck records']"
    MORE_OPTIONS="//div[@class='ant-dropdown-trigger more-option']"
    DELETE_PITCH_DECK="//span[text()='Delete']"
    DELETE_PITCH_CONFIRM="(//span[text()='Delete'])[2]"
