class my_startup_locators:
    PROFILE_ICON="//div[@class='ml-3 profile_container']"
    MY_STARTUP_HEADER="//h1[text()='My Startup']"
    IGNITE_HEADER="(//span[text()='ignite'])[1]"
    WADHWANI="(//span[text()='wadhwani'])[1]"
    IGNITE_VIEW_BUTTON="(//button[text()='View'])[2]"
    BASIC_INFORMATION="(//span//img)[3]"
    SAVE_BUTTON="//span[text()='Save']"
    YOUTUBE_VIDEO="//iframe[@class='media']"
    VALIDATE_VIEW_VENTURE_JOURNEY="//span[text()='View Venture Journey']"
    VENTURE_CODE="//span[text()='Venture code: ']"
    COHORT_NAME="//span[text()='Cohort Name: ']"
    PROGRAM_NAME="//span[text()='Program Name: ']"
    ABOUT_WADHWANI="(//img[@class='edit-pencil'])[2]"
    YOUTUBE_VIDEO_URL="//label[text()='Youtube Video URL']//following::input"
    VENTURE_TEAM="(//span//img)[4]"
    ADD_MEMBER="//span[text()='+ Add Member']"
    SEARCH_MEMBER="//input[@type='search']"
    SELECT_MEMBER="(//span[text()='Select'])[1]"
    ADD_MEMBERS_BUTTON="//span[text()='Add Members']"
    MEMBER_REMOVE_ICON="(//span[@class='ant-avatar ant-avatar-circle'])[5]//following::img[1]"
    CLOSE_ADD_MEMBERS_SECTION="//span[@class='ant-modal-close-x']"
    VENTURE_SUPPORT="//span[text()='Venture Support']"
    VENTURE_SUPPPORT_FACULTY="//p[text()='Faculty']"
    MILESTONE_TIMELINE="//span[text()='Milestone Timeline']"
    TEST_MILESTONE_CARD="(//div[contains(@class,'timeline-item')]//div[contains(@class,'milestone-card')])[1]"
    UPCOMING_ACTIVITIES="//h2[text()='Upcoming Activities']"
    MEETING_CARD="(//div[contains(@class,'card-wrapper')])[1]"
    WEBINAR_CARD="(//div[contains(@class,'card-wrapper')])[2]"
    RESOURCES="//h3[text()='Resources']"
    BROWSE_UPLOAD="//h3[text()='Browse & Upload']"
    FILE_NAME="//label[text()='File Name']"
    FILE_NAME_INPUT="//label[text()='File Name']/following::input[1]"
    FILE_NAME_LABEL="//label[text()='File Name']"
    SAVE_BUTTON="//span[text()='Save']"
    RESOURCES_CARD="//h2[text()='Resources']"
    MORE="//div[@class='ant-dropdown-trigger more-option']"
    VIEW_RESOURCE="//span[text()='View']"
    DELETE_RESOURCE="//span[text()='Delete']"
    LIFTOFF_SPARK="//span[text()='liftoff-spark']"
    WDHWANI="//span[text()='wdhwani']"
    LIFTOFF_SPARK_VIEW="(//button[text()='View'])[3]"
