class MyprofileLocators:
    MY_PROFILE_ICON="//span[text()='VS']"
    MY_PROFILE="//h1[text()='My Profile']"
    FIRST_NAME="//input[@id='name']"
    LAST_NAME="//input[@id='lastName']"
    SELECT_COUNTRY="//span[text()='India']"
    SELECT_CITY_ENGLISH="(//div[@id='Select City-search-input']//span)[1]"
    SELECT_CITY_SPANISH="(//div[@id='Seleccionar ciudad-search-input']//span)[1]"
    SELECT_CITY_WRAPPER_ENGLISH="//div[@id='Select City-search-input']"
    SELECT_CITY_WRAPPER_SPANISH="//div[@id='Seleccionar ciudad-search-input']"
    SELECT_CITY_INPUT_ENGLISH="//div[@id='Select City-search-input']//input"
    SELECT_CITY_INPUT_SPANISH="//div[@id='Seleccionar ciudad-search-input']//input"
    HYDERABAD_OPTION="//p[text()='Hyderabad']"
    BANGALORE_OPTION="//p[text()='Bangalore']"
    LANGUAGE="//div[@id='language']"
    SPANISH_LANGUAGE="//div[contains(@class, 'ant-select-item-option-content') and normalize-space(text())='Spanish']"
    ENGLISH_LANGUAGE="//div[contains(@class, 'ant-select-item-option-content') and normalize-space(text())='English']"
    MOBILE_NUMBER="//input[@id='mobile']"
    PROFILE_TYPE_DROPDOWN="(//label[text()='Profile type']/parent::div//span)[1]"
    PROFILE_TYPE="//span[text()='Exploring a new venture']"
    ROLE="//div[@id='Role-search-input']//following::span[@aria-label='caret-down'][1]"
    MANAGER_ROLE="//span[text()='Manager']"
    SAVE_BUTTON="//span[text()='Save']"
    SAVE_BUTTON_SPANISH="//span[text()='Guardar']"
    VALIDATE_SPANISH_LANGUAGE="//h4[text()='Información de Perfil']"