class cohort_home_locators:
    COHORTS="(//div[text()='Cohorts'])[1]"
    COHORTS_HEADING = "//h2[text()='Cohorts']"
    ACTIVE_TAB = "//p[contains(text(),'Active')]"
    SELECT_COHORT = "(//tr//td[number(text()) > 0])[1]"
    INACTIVE_TAB = "//p[contains(text(),'Inactive')]"
    SEARCH_INPUT = "//input[@placeholder='Search Cohort']"
    COHORT_DASHBOARD_TAB = "//p[text()='Cohort Dashboard']"
    VALIDATE_DOWNLOAD_EXCEL = "//span[text()='Click to download excel file']"
    GENERAL_INFO_TAB = "//p[text()='General Info']"
    BATCH_FACULTY = "//span[text()='Batch Faculty']"
    BATCH_FACULTY_CONTAINER = "//div[contains(@class,'member_icons_container')]"
    COHORT_MEMBERS_TAB = "//p[text()='Cohort Members']"
    COHORT_MEMBERS_COUNT = "//span[text()='Cohort Members (1)']"
    COHORT_MEMBERS_SECTION_TITLE = "(//p[contains(@class,'para1 regular section-title')])[1]"
    COHORT_MEMBERS_SECTION_SUBTITLE = "(//p[contains(@class,'para1 regular section-title')])[2]"
    COHORT_STARTUPS = "//p[text()='Cohort Startups']"
    COHORT_STARTUPS_COUNT = "//h4[text()='Cohort Startups (1)']"
    WF_LINK_BUTTON = "//div[contains(@class,'wf_link_button ')]"
    CREATE_NEW_COHORT = "//span[text()='Create New Cohort']"
    BATCH_NAME_INPUT = "//input[@id='batchName']"
    START_DATE_INPUT = "//input[@placeholder='start date']"
    SELECT_START_DATE = "//td[@class='ant-picker-cell ant-picker-cell-in-view ant-picker-cell-today']"
    END_DATE_INPUT = "//input[@placeholder='end date']"
    SELECT_END_DATE = "(//td[@class='ant-picker-cell ant-picker-cell-in-view'])[last()]"
    ADD_NUMBER_INPUT = "//input[@placeholder='add number']"
    SELECT_MAX_STUDENTS_ALLOWED_NUMBER = "//label[@title='Max students allowed']//following::input[1]"
    SELECT_MAX_STUDENTS_ALLOWED_PER_STARTUP = "//label[@title='Max students allowed per startup']//following::input[1]"
    CREATE_BUTTON = "//span[text()='Create']"
    OFFICE_HOURS_HEADING = "//h2[text()='Office Hours']"
    OFFICE_CREATE_BUTTON = "//span[text()='Create']"
    SESSION_TITLE_INPUT = "//label[text()='Enter Meeting Title']//following::input[1]"
    SELECT_DATE_INPUT = "//input[@placeholder='Select Date']"
    SELECT_TODAY_DATE = "//td[@class='ant-picker-cell ant-picker-cell-in-view ant-picker-cell-today']"
    SELECT_TIME_INPUT = "//span[@class='ant-select-selection-item']"
    OK_BUTTON = "//span[text()='OK']"
    CHECKBOX_INPUT = "//input[contains(@class,'ant-checkbox-input')]"
    CREATE_MEETING_BUTTON = "//span[text()='Create a Meeting']"
    OKAY_BUTTON = "//span[text()='Okay']"
    OFFICE_HOURS_MEETING_CARD = "//div[contains(@class,'card-wrapper meeting-card-wrapper happening_meeting')]"
    MEETING_TITLE = "//h5[text()='test']"
    DELETE_ICON = "//img[contains(@class,'delete-icon')]"
    RADIO_CHECK = "(//input[contains(@class,'radio-check')])[2]"
    REASON_TO_CANCEL = "(//label[contains(@class,'reason-text')])[2]"
    CANCEL_MEETING_BUTTON = "//button[contains(@class,'button-primary cancel-meeting-button  false')]"
    GO_BACK_TO_DASHBOARD_BUTTON = "//button[@class='button-link button-link  ']"


    





