class events_locators:
    EVENTS_TAB = "(//div[text()='Events'])[1]"
    EVENTS_HEADING = "//h2[text()='Events']"
    ADD_EVENT_BUTTON = "//span[text()='Add Event']"
    FILE_UPLOAD_IMAGE = "//span[contains(text(),'Upload Image')]"
    CROP_AND_SAVE_BUTTON = "//span[text()='Crop and Save']"
    EVENT_NAME = "//textarea[@placeholder='Enter the event name']"
    LANGUAGE_SELECTION = "//label[contains(text(),'Language')]/following::div[1]"
    LANGUAGE_OPTION = "//div[text()='English']"
    EVENT_TYPE_SELECTION = "//label[contains(text(),'Event Type')]/following::div[1]"
    EVENT_TYPE_OPTION = "(//div[text()='Meeting'])[1]"
    EVENT_DESCRIPTION = "//textarea[@placeholder='Event Description']"
    START_DATE_TIME = "//input[@placeholder='Start Date Time']"
    START_DATE_TIME_INPUT = "//td[@class='ant-picker-cell ant-picker-cell-in-view ant-picker-cell-today']"
    START_DATE_TIME_OK_BUTTON = "//span[text()='OK']"
    END_DATE_TIME = "//input[@placeholder='End Date Time']"
    END_DATE_TIME_INPUT = "(//td[@class='ant-picker-cell ant-picker-cell-in-view'])[last()]"
    END_DATE_TIME_OK_BUTTON = "//span[text()='OK']"
    REGISTRATION_LIMIT = "//input[@placeholder='Registration Limit']"
    ADD_SPEAKERS = "//span[text()='Add Speakers']"
    FIRST_NAME_INPUT = "//input[@placeholder='Enter the first name']"
    LAST_NAME_INPUT = "//input[@placeholder='Enter the last name']"
    EMAIL_INPUT = "//input[@placeholder='Enter the email Id']"
    SELECT_COUNTRY = "//p[text()='Country']/following::input[1]"
    INDIA_OPTION = "//div[text()='India']"
    SELECT_LOCATION = "//p[text()='Location']/following::input[1]"
    BANGALORE_OPTION = "//div[text()='Bangalore, Bangalore, Karnataka, India']"
    TITLE_INPUT = "//input[@placeholder='Enter your title/designation']"
    SUBMIT_BUTTON = "//span[text()='Submit']"
    CREATE_EVENT_NEXT_BUTTON = "//span[text()='Create Event & Next']"
    ADD_BY_EMAILS_RADIO = "//span[text()='Add by emails']/preceding::input[@type='radio'][1]"
    BULK_UPLOAD_INVITATION_BUTTON = "//span[text()='Bulk Upload Invitation']"
    CHOOSE_FILE_INPUT = "//input[@type='file']"
    UPLOAD_BUTTON = "//span[text()='Upload']"
    DOWNLOAD_BUTTON = "//span[text()='Download']"
    CLOSE_MODAL_BUTTON = "//span[@class='ant-modal-close-x']"
    DRAFT_TAB = "//p[contains(text(),'Draft')]"
    DELETE_BUTTON = "//span[text()='Delete']"
    DELETE_EVENT = "(//span[text()='Delete'])[2]"

