class program_managers_locators:
    MY_PROFILE= "//div[@class='ml-3 profile_container']"
    PROGRAM_MANAGERS_TAB = "//h1[text()='Program Managers']"
    PROGRAM_MANAGERS_HEADING = "//h2[text()='Manage Program Managers']"
    ADD_PROGRAM_MANAGER_BUTTON = "//span[text()='Add Program Manager']"
    FIRST_NAME_INPUT = "//input[@name='firstName']"
    LAST_NAME_INPUT = "//input[@name='lastName']"
    EMAIL_INPUT = "//input[@id='email']"
    MOBILE_NUMBER_INPUT = "//input[@placeholder='Mobile Number']"
    SELECT_COUNTRY = "//label[text()='Select Country']/following::div[contains(@class,'ant-select-selector')][1]"
    INDIA_OPTION = "//div[contains(@class,'ant-select-item-option-content') and normalize-space()='India']"
    SELECT_CITY = "//label[text()='Select City']/following::div[contains(@class,'ant-select-selector')][1]"
    BANGALORE_OPTION = "//div[contains(@class,'ant-select-item-option-content') and contains(normalize-space(),'Bangalore')]"
    CREATE_BUTTON = "//span[text()='Create']"
    