class program_managers_locators:
    MY_PROFILE= "//div[@class='ml-3 profile_container']"
    PROGRAM_MANAGERS_TAB = "//h1[text()='Program Managers']"
    PROGRAM_MANAGERS_HEADING = "//h2[text()='Manage Program Managers']"
    ADD_PROGRAM_MANAGER_BUTTON = "//span[text()='Add Program Manager']"
    FIRST_NAME_INPUT = "//input[@name='firstName']"
    LAST_NAME_INPUT = "//input[@name='lastName']"
    EMAIL_INPUT = "//input[@id='email']"
    MOBILE_NUMBER_INPUT = "//input[@placeholder='Mobile Number']"
    SELECT_COUNTRY = "//label[text()='Select Country']"
    INDIA_OPTION = "//div[text()='India']"
    # SELECT_CITY = "//div[contains(@class,'wf_animated')]//label[text()='Select City']"
    SELECT_CITY = "//div[text()='Bangalore, Bangalore, Karnataka, India']"
    CREATE_BUTTON = "//span[text()='Create']"
    